### ISSUE TITLE
Switching to lerna

### ISSUE THREAD

**Issue by saniko** [Botvy/Botvy-old#52]
Hi,
Just out of curiosity, why have you decided to switch from Nx to Lerna?
I'm interested in implementing monorepo solution myself.

Thanks

**Comment by YannickFricke** [comment]
Hey @saniko!

I switched back to Lerna cause of an issue of NX with the TypeScript transpiler.

You can see here the created issue on the TypeScript repository: https://github.com/microsoft/TypeScript/issues/38197

If you have any further questions feel free to ask! :)

**Comment by YannickFricke** [comment]
I am closing this for now.

If you have any further questions feel free to ask :)
